// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tnf.EventSourcing.EntityFrameworkCore.SqlServer;

namespace Tnf.EventSourcing.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerEventsDbContext))]
    [Migration("20181118161503_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tnf.EventSourcing.EntityFrameworkCore.StoredEvent", b =>
                {
                    b.Property<Guid>("AggregateId");

                    b.Property<long>("Version");

                    b.Property<string>("AggregateType")
                        .IsRequired();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<string>("Metadata");

                    b.HasKey("AggregateId", "Version");

                    b.HasIndex("AggregateId", "AggregateType");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
